### ISSUE TITLE
[BUG] Custom Model Upload Failure in OpenSearch 2.11 with Sparse Model

### ISSUE THREAD

**Issue by kuro96al** [opensearch-project/ml-commons#1710]
What is the bug?
In OpenSearch 2.11, when attempting to regist a custom sparse model (specifically, a SPLADE model), the process fails with an error message: "Find multiple model files, but expected only one". The zip file contains only two files: splade-eng.onnx and tokenizer.json.

How can one reproduce the bug?

Utilize OpenSearch 2.11. 
Regist a custom sparse model (SPLADE model).
The model regist process fails.
Error message displayed: "Find multiple model files, but expected only one".
What is the expected behavior?
The expected behavior is the successful registration of the custom sparse model without encountering an error.

What is your host/environment?

OS: [Specific OS not provided]
Version: OpenSearch 2.11
Plugins: [Specific plugins not provided, if any]
Do you have any screenshots?

Do you have any additional context?
The model being registered is a SPLADE model. The contents of the zip file being registered include only splade-eng.onnx and tokenizer.json, with no additional files present.

**Comment by kuro96al** [comment]
<img width="761" alt="スクリーンショット 2023-11-29 20 39 46" src="https://github.com/opensearch-project/ml-commons/assets/22856873/0a267c98-c875-46f6-993f-36dee865e4d8">

**Comment by dhrubo-os** [comment]
@xinyual could you please look into this issue? Thanks.

**Comment by xinyual** [comment]
Also, if you are using splade model, we recommend you to use our own pretrained model https://opensearch.org/docs/latest/ml-commons-plugin/pretrained-models/. It has better performance.

**Comment by kuro96al** [comment]
Thank you for the recommendation. Regarding English, I also agree that using the custom pretrained model you suggested would be beneficial. However, my primary interest lies in using and potentially training a Japanese language model with OpenSearch. Are there any published methods for creating ONNX or PyTorch models? I'm also interested in knowing if there are any resources available for learning how to train these models.

**Comment by xinyual** [comment]
You can use pytorch to have a try for generating TorchScript model. https://pytorch.org/docs/stable/jit.html

**Comment by kuro96al** [comment]
I tried converting it to PyTorch once, but it was unsuccessful. I would appreciate it if you could provide me with some examples of model conversions that are available in OpenSearch.

**Comment by zhichao-aws** [comment]
@kuro96al Here is a demo script to trace a .pt model which can be used in OpenSearch:
```
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM

class NeuralSparseModel(torch.nn.Module):
    def __init__(self,bert):
        super().__init__()
        self.bert = bert
        
    def forward(self, input: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        result = self.bert(input_ids=input["input_ids"],attention_mask=input["attention_mask"])[0]
        values, _ = torch.max(result*input["attention_mask"].unsqueeze(-1), dim=1)
        values = torch.log(1 + torch.relu(values))
        return {"output":values}

bert = AutoModelForMaskedLM.from_pretrained("/path-to-your-bert-mlm-model/")
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = NeuralSparseModel(bert)

text = ['sample text '*10]*4
input = tokenizer(text,
                            add_special_tokens=True,
                            padding="longest",  # pad to max sequence length in batch
                            truncation="longest_first",  # truncates to self.max_length
                            max_length=512,
                            return_attention_mask=True,
                            return_token_type_ids=False,
                            return_tensors="pt"
                 )
traced_model = torch.jit.trace(NeuralSparseModel(bert_bi), dict(input),strict=False)
torch.jit.save(traced_model, "target/save/path")
```

You can replace the model/tokenizer path and target save path based on your requirements

**Comment by kuro96al** [comment]
Thank you very much. I will refer to what I have received and try it out with a Japanese model.

**Comment by gitcarbs** [comment]
@kuro96al how did you create the zip file, was it using the macOS Compress feature?

I encountered a similar issue, and it turned out my zip file contained that additional `__MACOSX` directory. Its presence throws off the Opensearch model loading function.

I suggest you rebuild the zip, using this command to ensure you only get the relevant files in the zip

```
zip -r -X model.zip * 
```

**Comment by marevol** [comment]
I tried a custom sparse encoding model on OpenSearch 2.11.1, and it works.
```
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM
from typing import Dict

model_path = "naver_ecir23-scratch-tydi-japanese-splade-torch_script"
# !mkdir -p {model_path}

class NeuralSparseModel(torch.nn.Module):
    def __init__(self,bert):
        super().__init__()
        self.bert = bert
        
    def forward(self, input: Dict[str, torch.Tensor]) -> Dict[str, torch.Tensor]:
        result = self.bert(input_ids=input["input_ids"],attention_mask=input["attention_mask"])[0]
        values, _ = torch.max(result*input["attention_mask"].unsqueeze(-1), dim=1)
        values = torch.log(1 + torch.relu(values))
        return {"output":values}

tokenizer = AutoTokenizer.from_pretrained("naver/ecir23-scratch-tydi-japanese-splade")
bert = AutoModelForMaskedLM.from_pretrained("naver/ecir23-scratch-tydi-japanese-splade")
model = NeuralSparseModel(bert)

text = ['sample text '*10]*4
input = tokenizer(text,
                            add_special_tokens=True,
                            padding=True,
                            truncation=True,
                            max_length=512,
                            return_attention_mask=True,
                            return_token_type_ids=False,
                            return_tensors="pt"
                 )
traced_model = torch.jit.trace(model, dict(input),strict=False)
torch.jit.save(traced_model, f"{model_path}/ecir23-scratch-tydi-japanese-splade.pt")
tokenizer.save_pretrained(model_path)
# !cd {model_path}
# !zip ../{model_path}.zip *
# !shasum -a 256 ../{model_path}.zip
```
Then, copy the zip file to a directory that OpenSearch can read.
To register it as a custom model, the request is as follows:
```
$ curl -XPOST "http://localhost:9200/_plugins/_ml/models/_register" -H 'Content-Type: application/json' -d'
{
  "name": "naver/ecir23-scratch-tydi-japanese-splade_torch_script",
  "version": "1.0.0",
  "model_group_id": "<your group model id>",
  "description": "This is a sparse encoder model.",
  "function_name": "SPARSE_ENCODING",
  "model_format": "TORCH_SCRIPT",
  "model_content_hash_value": "<hash value from shasum>",
        "url": "file:///usr/share/opensearch/data/naver_ecir23-scratch-tydi-japanese-splade-torch_script.zip",
   "model_config": {
      "model_type": "bert",
     "embedding_dimension": 768,
    "framework_type": "sentence_transformers"
  }
}'
```
So, TorchScript model looks good to me.

**Comment by kuro96al** [comment]
This is a different issue, but do you know a solution for this?
{
  "model_id": "oHSpVY4B3eZG-EXv_cbd",
  "task_type": "DEPLOY_MODEL",
  "function_name": "SPARSE_ENCODING",
  "state": "FAILED",
  "worker_node": [
    "ybdsNWCpRT6pexqyy-eR1A",
    "SRiqjhfdRV2udioS_rO5mA",
    "TsBfIkraTvWi0yFJI_UMUw"
  ],
  "create_time": 1710835574640,
  "last_update_time": 1710835581907,
  "error": """{"ybdsNWCpRT6pexqyy-eR1A":"Exception java.lang.IllegalArgumentException: Invalid characters in hostname [in thread \"opensearch[opensearch-cluster-master-0][opensearch_ml_deploy][T#3]\"]","SRiqjhfdRV2udioS_rO5mA":"Exception java.lang.IllegalArgumentException: Invalid characters in hostname [in thread \"opensearch[opensearch-cluster-master-2][opensearch_ml_deploy][T#4]\"]","TsBfIkraTvWi0yFJI_UMUw":"Exception java.lang.IllegalArgumentException: Invalid characters in hostname [in thread \"opensearch[opensearch-cluster-master-1][opensearch_ml_deploy][T#3]\"]"}""",
  "is_async": true
}

**Comment by zane-neo** [comment]
Is there any error stack trace you can find on your cluster?

**Comment by xinyual** [comment]
@kuro96al Can you provide your register and deploy request body here?

**Comment by kuro96al** [comment]
I attempted the process again with version 2.12.0. Here is the log for your review.
It seems likely that the cause is that the worker node's ID (hostname) contains an underscore.
```
{
  "model_id": "4IkQX44Boe7kBZjFFaWy",
  "task_type": "DEPLOY_MODEL",
  "function_name": "SPARSE_ENCODING",
  "state": "FAILED",
  "worker_node": [
    "lf5waQHlTZSusfZtL_4HGA",
    "ymOmvHY7TzKzt9m21G-2sg",
    "N1vza14WSb2G1Y59GEpy6Q"
  ],
  "create_time": 1710991907939,
  "last_update_time": 1710991915629,
  "error": """{"lf5waQHlTZSusfZtL_4HGA":"Invalid character \\u005f in hostname","ymOmvHY7TzKzt9m21G-2sg":"Invalid character \\u005f in hostname","N1vza14WSb2G1Y59GEpy6Q":"Invalid character \\u005f in hostname"}""",
  "is_async": true
}
```

```
[2024-03-21T03:31:55,180][ERROR][o.o.m.m.MLModelManager   ] [opensearch-cluster-master-0] Failed to retrieve model 4IkQX44Boe7kBZjFFaWy
org.opensearch.ml.common.exception.MLException: Failed to deploy model 4IkQX44Boe7kBZjFFaWy
        at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:294) ~[?:?]
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:571) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.loadModel(DLModel.java:247) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.initModel(DLModel.java:139) ~[?:?]
        at org.opensearch.ml.engine.MLEngine.deploy(MLEngine.java:125) ~[?:?]
        at org.opensearch.ml.model.MLModelManager.lambda$deployModel$51(MLModelManager.java:1020) ~[?:?]
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.12.0.jar:2.12.0]
        at org.opensearch.ml.model.MLModelManager.lambda$retrieveModelChunks$72(MLModelManager.java:1553) [opensearch-ml-2.12.0.0.jar:2.12.0.0]
        at org.opensearch.core.action.ActionListener$1.onResponse(ActionListener.java:82) [opensearch-core-2.12.0.jar:2.12.0]
        at org.opensearch.action.support.ThreadedActionListener$1.doRun(ThreadedActionListener.java:78) [opensearch-2.12.0.jar:2.12.0]
        at org.opensearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:913) [opensearch-2.12.0.jar:2.12.0]
        at org.opensearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:52) [opensearch-2.12.0.jar:2.12.0]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) [?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) [?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.ExceptionInInitializerError
        at org.opensearch.ml.engine.algorithms.DLModel.doLoadModel(DLModel.java:185) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:280) ~[?:?]
        ... 14 more
Caused by: java.lang.IllegalArgumentException: Invalid character \u005f in hostname
        at java.base/java.net.HostPortrange.toLowerCase(HostPortrange.java:190) ~[?:?]
        at java.base/java.net.HostPortrange.<init>(HostPortrange.java:150) ~[?:?]
        at java.base/java.net.URLPermission$Authority.<init>(URLPermission.java:533) ~[?:?]
        at java.base/java.net.URLPermission.parseURI(URLPermission.java:501) ~[?:?]
        at java.base/java.net.URLPermission.init(URLPermission.java:210) ~[?:?]
        at java.base/java.net.URLPermission.<init>(URLPermission.java:190) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.URLtoSocketPermission(HttpURLConnection.java:1158) ~[?:?]
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1107) ~[?:?]
        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:141) ~[?:?]
        at ai.djl.util.Ec2Utils.openConnection(Ec2Utils.java:163) ~[?:?]
        at ai.djl.util.Ec2Utils.callHome(Ec2Utils.java:107) ~[?:?]
        at ai.djl.engine.Engine.initEngine(Engine.java:93) ~[?:?]
        at ai.djl.engine.Engine.<clinit>(Engine.java:61) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.doLoadModel(DLModel.java:185) ~[?:?]
        at org.opensearch.ml.engine.algorithms.DLModel.lambda$loadModel$1(DLModel.java:280) ~[?:?]
        ... 14 more
```

**Comment by xinyual** [comment]
Can you provide your request body? It seems your URL has something wrong.

**Comment by kuro96al** [comment]
POST /_plugins/_ml/models/Rs17ZY4Bkp8k158ojM0N/_deploy

POST _plugins/_ml/models/_register
{
  "name": "naver/ecir23-scratch-tydi-japanese-splade_torch_script",
  "version": "1.0.0",
  "model_group_id": "3397ZY4BCNjHMSbAdraI",
  "description": "This is a sparse encoder model.",
  "function_name": "SPARSE_ENCODING",
  "model_format": "TORCH_SCRIPT",
  "model_content_hash_value": "<model hash>",
        "url": "<model url>",
   "model_config": {
      "model_type": "bert",
     "embedding_dimension": 768,
    "framework_type": "sentence_transformers"
  }
}

**Comment by xinyual** [comment]
Sorry for late reply. It seems you are right. The problem is from the DJL and it is because the wrong host.

**Comment by dhrubo-os** [comment]
Closing the issue, Please feel free to open the issue again if needed.

**Comment by kuro96al** [comment]
@xinyual Does this mean there is an issue with the implementation of OpenSearch? (Can it be circumvented with settings or is my configuration not modern enough?)"

**Comment by xinyual** [comment]
@kuro96al Hi, do you try opensearch on an EC2? If so, could you please provide your instance-id or check whether there is an underscore inside the instance-id? I check the code, it seems the url is not related with work node name and it is the implementation of DJL which opensearch depends on. It is related to your instance-id/region.

**Comment by kuro96al** [comment]
@xinyual We are using an on-premises environment. We are installing using Helm on a Kubernetes (k8s) cluster.

https://github.com/opensearch-project/helm-charts

**Comment by xinyual** [comment]
@kuro96al Can you provide some doc so I can follow to reproduce such problem? Also, could you please provide the config file to define some environment variables?

**Comment by kuro96al** [comment]
```
---
image:
  repository: "{{ opensearch_image }}"
  tag: "{{ opensearch_version }}"
resources: {{ container_opensearch_resources }}
opensearchLifecycle:
  preStop:
    exec:
      command: ["/bin/sh", "-c", "until curl -m 10 -s http://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"'; do sleep 5; done"]
keystore:
  - secretName: keystore-secrets
config:
  opensearch.yml: |
    cluster.name: opensearch-cluster

    # Bind to all interfaces because we don't know what IP address Docker will assign to us.
    network.host: 0.0.0.0

    plugins:
      security:
        disabled: true
    cluster.indices.replication.strategy: 'SEGMENT'
    s3.client.default.endpoint: test:80
    s3.client.default.protocol: http
    s3.client.default.region: "dev"
    s3.client.default.path_style_access: "true"
    node.attr.remote_store.segment.repository: my-repo
    node.attr.remote_store.translog.repository: my-repo
    node.attr.remote_store.state.repository: my-repo
    node.attr.remote_store.repository.my-repo.type: s3
    node.attr.remote_store.repository.my-repo.settings.bucket: test
    node.attr.remote_store.repository.my-repo.settings.base_path: store-2
    node.attr.remote_store.repository.my-repo.settings.region: "dev"
service:
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/_prometheus/metrics'
    prometheus.io/port: '9200'
opensearchJavaOpts: "{{ opensearch_java_opts }}"
persistence:
  enabled: false
extraEnvs:
  - name: DISABLE_INSTALL_DEMO_CONFIG
    value: "true"
extraVolumes:
  - name: "opensearch-cluster-master"
    emptyDir: {}
extraVolumeMounts:
  - name: "opensearch-cluster-master"
    mountPath: /usr/share/opensearch/data
```
